version: "3.9"
   
services:
#  db:
#    image:  postgis/postgis:12-master
#    restart: on-failure
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
  db:
    container_name: db
    image: postgis/postgis:12-master
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
#    networks:
#      - webnet
    expose:
      - 5432
  #  env_file: ./config/.env
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
#  healthcheck:
#    test: [ "CMD", "pg_isready", "-U", "postgres" ]
#    interval: 10s
#    timeout: 5s
#    retries: 5
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@test.com"
      PGADMIN_DEFAULT_PASSWORD: "admin_"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    restart: unless-stopped
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      DJANGO_DEBUG: 1
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres'
      DATABASE_HOST: 'db'
    ports:
      - "8000:8000"

    depends_on:
      - db
    links:
      - db:db


networks:
  postgres:
    driver: bridge
volumes:
  db-data:
  postgres:
  pgadmin: